// You may write any gradle buildscript component in this file
// This file is automatically applied after build.gradle + dependencies.gradle is ran

// If you wish to use the default helper methods, uncomment the line below
// apply from: 'gradle/scripts/helpers.gradle'
jar {
    manifest {
        attributes(
                'MixinConfigs': 'mixins.immersivefixes.json'
        )
    }
}
tasks.register('devJar', Jar) {
    dependsOn classes
    from sourceSets.main.output
    archiveClassifier = 'dev'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

artifacts {
    archives devJar
}

tasks.named('reobfJar').configure { mustRunAfter tasks.named('devJar') }

assemble.dependsOn devJar
